/*
 * defaults.h
 *
 *  Created on: 29 de set de 2020
 *      Author: rfranca
 */

#ifndef UTILS_DEFAULTS_H_
#define UTILS_DEFAULTS_H_

#include "../simucam_definitions.h"
#include "meb.h"
#include "configs_simucam.h"
#include "../driver/comm/comm.h"

//! [constants definition]
#define DEFT_MEB_DEFS_ID_LOWER_LIM      0
#define DEFT_FEE_DEFS_ID_LOWER_LIM      1000
#define DEFT_NUC_DEFS_ID_LOWER_LIM      10000
#define DEFT_NUC_DEFS_ID_RESERVED       0xFFFF
#define DEFT_RETRANSMISSION_TIMEOUT     5
//! [constants definition]

//! [public module structs definition]

/* MEB defaults */
typedef struct DeftMebDefaults {
	TDefaults xDebug; /* Debug */
	alt_u8 ucSyncSource; /* SyncSource */
	alt_u32 usiExposurePeriod; /* Exposure Period */
	bool bEventReport; /* Event Report */
	bool bLogReport; /* Log Report */
} TDeftMebDefaults;

/* FEE defaults */
typedef struct DeftFeeDefaults {
	TRmapMemDebArea *vpxRmapDebMem; /* RMAP DEB Memory */
	TRmapMemAebArea *vpxRmapAebMem[N_OF_CCD]; /* RMAP AEB Memory */
	TSpwcLinkConfig xSpwLinkConfig; /* SpaceWire Link Config */
	bool bTimecodebTransEn; /* SpaceWire Timecode Transmission Enable */
	alt_u8 ucRmapLogicAddr; /* RMAP Logical Address */
	alt_u8 ucRmapKey; /* RMAP Key */
} TDeftFeeDefaults;

/* NUC defaults */
typedef struct DeftNucDefaults {
	TConfEth xEthernet; /* Ethernet */
} TDeftNucDefaults;
//! [public module structs definition]

/* Defaults Enumeration */
enum DefaultId {
	// MEB
	//eDefReadOutOrder0 = 0, eDefReadOutOrder1, eDefReadOutOrder2, eDefReadOutOrder3,
	eDefOverScanSerial = 4,
	eDefPreScanSerial, eDefOLN, eDefCols, eDefRows,	eDefSyncPeriod,
	eDefPreBtSync, eDefBufferOverflowEn, eDefStartDelay, eDefSkipDelay,	eDefLineDelay,
	eDefADCPixelDelay, eDefRmapKey, eDefMebLogicalAddr, eDefSpwLinkStart, eDefLinkNFEE0,
	eDefDebugLevel, eDefPatternType, eDefGuardNFEEDelay, eDefDataProtId, eDefDpuLogicalAddr,
	//eDefSpwPLength,
	eDefSync_Source = 26,
	//eDefEP,
	eDefEventReport = 28, eDefLogReport,

	// FEE - LESIA Only
//	eDefVStart = 1000, eDefVEnd, eDefChargeInjectionWidth, eDefChargeInjectionGap, eDefParallelToiPeriod,
//	eDefParallelClkOverlap, eDefCcdReadoutOrder1stCcd, eDefCcdReadoutOrder2ndCcd, eDefCcdReadoutOrder3rdCcd, eDefCcdReadoutOrder4thCcd,
//	eDefNFinalDump, eDefHEnd, eDefChargeInjectionEn, eDefTriLevelClkEn, eDefImgClkDir,
//	eDefRegClkDir, eDefPacketSize, eDefIntSyncPeriod, eDefTrapPumpingDwellCounter, eDefSyncSel,
//	eDefSensorSel, eDefDigitiseEn, eDefDGEn, eDefCcdReadEn, eDefReg5ConfigReserved,
//	eDefCcd1WinListPtr, eDefCcd1PktorderListPtr, eDefCcd1WinListLength, eDefCcd1WinSizeX, eDefCcd1WinSizeY,
//	eDefReg8ConfigReserved, eDefCcd2WinListPtr, eDefCcd2PktorderListPtr, eDefCcd2WinListLength, eDefCcd2WinSizeX,
//	eDefCcd2WinSizeY, eDefReg11ConfigReserved, eDefCcd3WinListPtr, eDefCcd3PktorderListPtr, eDefCcd3WinListLength,
//	eDefCcd3WinSizeX, eDefCcd3WinSizeY, eDefReg14ConfigReserved, eDefCcd4WinListPtr, eDefCcd4PktorderListPtr,
//	eDefCcd4WinListLength, eDefCcd4WinSizeX, eDefCcd4WinSizeY, eDefReg17ConfigReserved, eDefCcdVodConfig,
//	eDefCcd1VrdConfig, eDefCcd2VrdConfig0, eDefCcd2VrdConfig1, eDefCcd3VrdConfig, eDefCcd4VrdConfig,
//	eDefCcdVgdConfig0, eDefCcdVgdConfig1, eDefCcdVogConfig, eDefCcdIgHiConfig, eDefCcdIgLoConfig,
//	eDefReg21ConfigReserved0, eDefCcdModeConfig, eDefReg21ConfigReserved1, eDefClearErrorFlag, eDefReg22ConfigReserved,
//	eDefCcd1LastEPacket, eDefCcd1LastFPacket, eDefCcd2LastEPacket, eDefReg23ConfigReserved, eDefCcd2LastFPacket,
//	eDefCcd3LastEPacket, eDefCcd3LastFPacket, eDefReg24ConfigReserved, eDefCcd4LastEPacket, eDefCcd4LastFPacket,
//	eDefSurfaceInversionCounter, eDefReg25ConfigReserved, eDefReadoutPauseCounter, eDefTrapPumpingShuffleCounter,

	// FEE - HK Fields - LESIA Only
//	eDefTouSense1 = 2000, eDefTouSense2, eDefTouSense3, eDefTouSense4, eDefTouSense5,
//	eDefTouSense6, eDefCcd1Ts, eDefCcd2Ts, eDefCcd3Ts, eDefCcd4Ts,
//	eDefPrt1, eDefPrt2, eDefPrt3, eDefPrt4, eDefPrt5,
//	eDefZeroDiffAmp, eDefCcd1VodMon, eDefCcd1VogMon, eDefCcd1VrdMonE, eDefCcd2VodMon,
//	eDefCcd2VogMon, eDefCcd2VrdMonE, eDefCcd3VodMon, eDefCcd3VogMon, eDefCcd3VrdMonE,
//	eDefCcd4VodMon, eDefCcd4VogMon, eDefCcd4VrdMonE, eDefVccd, eDefVrclkMon,
//	eDefViclk, eDefVrclkLow, eDef5vbPosMon, eDef5vbNegMon, eDef3v3bMon,
//	eDef2v5aMon, eDef3v3dMon, eDef2v5dMon, eDef1v5dMon, eDef5vrefMon,
//	eDefVccdPosRaw, eDefVclkPosRaw, eDefVan1PosRaw, eDefVan3NegMon, eDefVan2PosRaw,
//	eDefVdigRaw, eDefVdigRaw2, eDefViclkLow, eDefCcd1VrdMonF, eDefCcd1VddMon,
//	eDefCcd1VgdMon, eDefCcd2VrdMonF, eDefCcd2VddMon, eDefCcd2VgdMon, eDefCcd3VrdMonF,
//	eDefCcd3VddMon, eDefCcd3VgdMon, eDefCcd4VrdMonF, eDefCcd4VddMon, eDefCcd4VgdMon,
//	eDefIgHiMon, eDefIgLoMon, eDefTsenseA, eDefTsenseB, eDefSpwStatusSpwStatusReserved,
//	eDefReg32HkReserved, eDefReg33HkReserved, eDefOpMode, eDefErrorFlagsErrorFlagsReserved, eDefFpgaMinorVersion,
//	eDefFpgaMajorVersion, eDefBoardId, eDefReg35HkReserved,

	// FEE - SPW
	//eDefSPW_LinkStart = 3000,
	eDefSPW_Autostart = 3001, eDefSPW_LinkSpeed, eDefTimeCodeEnable, //eDefFeeLogicalAddr, eDefFeeKey,

	// FEE - DEB - DLR Only
	eDefDebAreaCritCfg_DtcAebOnoff_bAebIdx3 = 4000, eDefDebAreaCritCfg_DtcAebOnoff_bAebIdx2, eDefDebAreaCritCfg_DtcAebOnoff_bAebIdx1, eDefDebAreaCritCfg_DtcAebOnoff_bAebIdx0, eDefDebAreaCritCfg_DtcPllReg0_bPfdfc,
	eDefDebAreaCritCfg_DtcPllReg0_bGtme, eDefDebAreaCritCfg_DtcPllReg0_bHoldtr, eDefDebAreaCritCfg_DtcPllReg0_bHoldf, eDefDebAreaCritCfg_DtcPllReg0_ucOthers, eDefDebAreaCritCfg_DtcPllReg1_uliOthers,
	eDefDebAreaCritCfg_DtcPllReg2_uliOthers, eDefDebAreaCritCfg_DtcPllReg3_uliOthers, eDefDebAreaCritCfg_DtcFeeMod_ucOperMod, eDefDebAreaCritCfg_DtcImmOnmod_bImmOn,

	eDefDebAreaGenCfg_CfgDtcInMod_ucT7InMod = 4200, eDefDebAreaGenCfg_CfgDtcInMod_ucT6InMod, eDefDebAreaGenCfg_CfgDtcInMod_ucT5InMod, eDefDebAreaGenCfg_CfgDtcInMod_ucT4InMod, eDefDebAreaGenCfg_CfgDtcInMod_ucT3InMod,
	eDefDebAreaGenCfg_CfgDtcInMod_ucT2InMod, eDefDebAreaGenCfg_CfgDtcInMod_ucT1InMod, eDefDebAreaGenCfg_CfgDtcInMod_ucT0InMod, eDefDebAreaGenCfg_CfgDtcWdwSiz_ucWSizX, eDefDebAreaGenCfg_CfgDtcWdwSiz_ucWSizY,
	eDefDebAreaGenCfg_CfgDtcWdwIdx_usiWdwIdx4, eDefDebAreaGenCfg_CfgDtcWdwIdx_usiWdwLen4, eDefDebAreaGenCfg_CfgDtcWdwIdx_usiWdwIdx3, eDefDebAreaGenCfg_CfgDtcWdwIdx_usiWdwLen3, eDefDebAreaGenCfg_CfgDtcWdwIdx_usiWdwIdx2,
	eDefDebAreaGenCfg_CfgDtcWdwIdx_usiWdwLen2, eDefDebAreaGenCfg_CfgDtcWdwIdx_usiWdwIdx1, eDefDebAreaGenCfg_CfgDtcWdwIdx_usiWdwLen1, eDefDebAreaGenCfg_CfgDtcOvsPat_ucOvsLinPat, eDefDebAreaGenCfg_CfgDtcSizPat_usiNbLinPat,
	eDefDebAreaGenCfg_CfgDtcSizPat_usiNbPixPat, eDefDebAreaGenCfg_CfgDtcTrg25S_ucN25SNCyc, eDefDebAreaGenCfg_CfgDtcSelTrg_bTrgSrc, eDefDebAreaGenCfg_CfgDtcFrmCnt_usiPsetFrmCnt, eDefDebAreaGenCfg_CfgDtcSelSyn_bSynFrq,
	eDefDebAreaGenCfg_CfgDtcRstCps_bRstSpw, eDefDebAreaGenCfg_CfgDtcRstCps_bRstWdg, eDefDebAreaGenCfg_CfgDtc25SDly_uliN25SDly, eDefDebAreaGenCfg_CfgDtcTmodConf_uliReserved, eDefDebAreaGenCfg_CfgDtcSpwCfg_ucTimecode,

	eDefDebAreaHk_DebStatus_ucOperMod = 4400, eDefDebAreaHk_DebStatus_ucEdacListCorrErr, eDefDebAreaHk_DebStatus_ucEdacListUncorrErr, eDefDebAreaHk_DebStatus_ucOthers, eDefDebAreaHk_DebStatus_bVdigAeb4,
	eDefDebAreaHk_DebStatus_bVdigAeb3, eDefDebAreaHk_DebStatus_bVdigAeb2, eDefDebAreaHk_DebStatus_bVdigAeb1, eDefDebAreaHk_DebStatus_ucWdwListCntOvf, eDefDebAreaHk_DebStatus_bWdg,
	eDefDebAreaHk_DebOvf_bRowActList8, eDefDebAreaHk_DebOvf_bRowActList7, eDefDebAreaHk_DebOvf_bRowActList6, eDefDebAreaHk_DebOvf_bRowActList5, eDefDebAreaHk_DebOvf_bRowActList4,
	eDefDebAreaHk_DebOvf_bRowActList3, eDefDebAreaHk_DebOvf_bRowActList2, eDefDebAreaHk_DebOvf_bRowActList1, eDefDebAreaHk_DebAhk1_usiVdigIn, eDefDebAreaHk_DebAhk1_usiVio,
	eDefDebAreaHk_DebAhk2_usiVcor, eDefDebAreaHk_DebAhk2_usiVlvd, eDefDebAreaHk_DebAhk3_usiDebTemp,

	// FEE - AEB - DLR Only
	eDefAeb1AreaCritCfg_AebControl_ucReserved0 = 5000, eDefAeb1AreaCritCfg_AebControl_ucNewState, eDefAeb1AreaCritCfg_AebControl_bSetState, eDefAeb1AreaCritCfg_AebControl_bAebReset, eDefAeb1AreaCritCfg_AebControl_uliOthers,
	eDefAeb1AreaCritCfg_AebConfig_uliOthers, eDefAeb1AreaCritCfg_AebConfigKey_uliKey, eDefAeb1AreaCritCfg_AebConfigAit_uliOthers, eDefAeb1AreaCritCfg_AebConfigPattern_ucPatternCcdid, eDefAeb1AreaCritCfg_AebConfigPattern_usiPatternCols,
	eDefAeb1AreaCritCfg_AebConfigPattern_ucReserved, eDefAeb1AreaCritCfg_AebConfigPattern_usiPatternRows, eDefAeb1AreaCritCfg_VaspI2CControl_uliOthers, eDefAeb1AreaCritCfg_DacConfig1_uliOthers, eDefAeb1AreaCritCfg_DacConfig2_uliOthers,
	eDefAeb1AreaCritCfg_Reserved20_uliReserved, eDefAeb1AreaCritCfg_PwrConfig1_ucTimeVccdOn, eDefAeb1AreaCritCfg_PwrConfig1_ucTimeVclkOn, eDefAeb1AreaCritCfg_PwrConfig1_ucTimeVan1On, eDefAeb1AreaCritCfg_PwrConfig1_ucTimeVan2On,
	eDefAeb1AreaCritCfg_PwrConfig2_ucTimeVan3On, eDefAeb1AreaCritCfg_PwrConfig2_ucTimeVccdOff, eDefAeb1AreaCritCfg_PwrConfig2_ucTimeVclkOff, eDefAeb1AreaCritCfg_PwrConfig2_ucTimeVan1Off, eDefAeb1AreaCritCfg_PwrConfig3_ucTimeVan2Off,
	eDefAeb1AreaCritCfg_PwrConfig3_ucTimeVan3Off,

	eDefAeb1AreaGenCfg_Adc1Config1_uliOthers = 5200, eDefAeb1AreaGenCfg_Adc1Config2_uliOthers, eDefAeb1AreaGenCfg_Adc1Config3_uliOthers, eDefAeb1AreaGenCfg_Adc2Config1_uliOthers, eDefAeb1AreaGenCfg_Adc2Config2_uliOthers,
	eDefAeb1AreaGenCfg_Adc2Config3_uliOthers, eDefAeb1AreaGenCfg_Reserved118_uliReserved, eDefAeb1AreaGenCfg_Reserved11C_uliReserved, eDefAeb1AreaGenCfg_SeqConfig1_uliOthers, eDefAeb1AreaGenCfg_SeqConfig2_uliOthers,
	eDefAeb1AreaGenCfg_SeqConfig3_uliOthers, eDefAeb1AreaGenCfg_SeqConfig4_uliOthers, eDefAeb1AreaGenCfg_SeqConfig5_uliOthers, eDefAeb1AreaGenCfg_SeqConfig6_uliOthers, eDefAeb1AreaGenCfg_SeqConfig7_uliReserved,
	eDefAeb1AreaGenCfg_SeqConfig8_uliReserved, eDefAeb1AreaGenCfg_SeqConfig9_ucReserved0, eDefAeb1AreaGenCfg_SeqConfig9_usiFtLoopCnt, eDefAeb1AreaGenCfg_SeqConfig9_bLt0Enabled, eDefAeb1AreaGenCfg_SeqConfig9_bReserved1,
	eDefAeb1AreaGenCfg_SeqConfig9_usiLt0LoopCnt, eDefAeb1AreaGenCfg_SeqConfig10_bLt1Enabled, eDefAeb1AreaGenCfg_SeqConfig10_bReserved0, eDefAeb1AreaGenCfg_SeqConfig10_usiLt1LoopCnt, eDefAeb1AreaGenCfg_SeqConfig10_bLt2Enabled,
	eDefAeb1AreaGenCfg_SeqConfig10_bReserved1, eDefAeb1AreaGenCfg_SeqConfig10_usiLt2LoopCnt, eDefAeb1AreaGenCfg_SeqConfig11_bLt3Enabled, eDefAeb1AreaGenCfg_SeqConfig11_bReserved, eDefAeb1AreaGenCfg_SeqConfig11_usiLt3LoopCnt,
	eDefAeb1AreaGenCfg_SeqConfig11_usiPixLoopCntWord1, eDefAeb1AreaGenCfg_SeqConfig12_usiPixLoopCntWord0, eDefAeb1AreaGenCfg_SeqConfig12_bPcEnabled, eDefAeb1AreaGenCfg_SeqConfig12_bReserved, eDefAeb1AreaGenCfg_SeqConfig12_usiPcLoopCnt,
	eDefAeb1AreaGenCfg_SeqConfig13_ucReserved0, eDefAeb1AreaGenCfg_SeqConfig13_usiInt1LoopCnt, eDefAeb1AreaGenCfg_SeqConfig13_ucReserved1, eDefAeb1AreaGenCfg_SeqConfig13_usiInt2LoopCnt, eDefAeb1AreaGenCfg_SeqConfig14_uliOthers,

	eDefAeb1AreaHk_AebStatus_ucAebStatus = 5400, eDefAeb1AreaHk_AebStatus_ucOthers0, eDefAeb1AreaHk_AebStatus_usiOthers1, eDefAeb1AreaHk_Timestamp1_uliTimestampDword1, eDefAeb1AreaHk_Timestamp2_uliTimestampDword0,
	eDefAeb1AreaHk_AdcRdDataTVaspL_uliOthers, eDefAeb1AreaHk_AdcRdDataTVaspR_uliOthers, eDefAeb1AreaHk_AdcRdDataTBiasP_uliOthers, eDefAeb1AreaHk_AdcRdDataTHkP_uliOthers, eDefAeb1AreaHk_AdcRdDataTTou1P_uliOthers,
	eDefAeb1AreaHk_AdcRdDataTTou2P_uliOthers, eDefAeb1AreaHk_AdcRdDataHkVode_uliOthers, eDefAeb1AreaHk_AdcRdDataHkVodf_uliOthers, eDefAeb1AreaHk_AdcRdDataHkVrd_uliOthers, eDefAeb1AreaHk_AdcRdDataHkVog_uliOthers,
	eDefAeb1AreaHk_AdcRdDataTCcd_uliOthers, eDefAeb1AreaHk_AdcRdDataTRef1KMea_uliOthers, eDefAeb1AreaHk_AdcRdDataTRef649RMea_uliOthers, eDefAeb1AreaHk_AdcRdDataHkAnaN5V_uliOthers, eDefAeb1AreaHk_AdcRdDataSRef_uliOthers,
	eDefAeb1AreaHk_AdcRdDataHkCcdP31V_uliOthers, eDefAeb1AreaHk_AdcRdDataHkClkP15V_uliOthers, eDefAeb1AreaHk_AdcRdDataHkAnaP5V_uliOthers, eDefAeb1AreaHk_AdcRdDataHkAnaP3V3_uliOthers, eDefAeb1AreaHk_AdcRdDataHkDigP3V3_uliOthers,
	eDefAeb1AreaHk_AdcRdDataAdcRefBuf2_uliOthers, eDefAeb1AreaHk_VaspRdConfig_usiOthers, eDefAeb1AreaHk_RevisionId1_uliOthers, eDefAeb1AreaHk_RevisionId2_uliOthers,

	eDefAeb2AreaCritCfg_AebControl_ucReserved0 = 6000, eDefAeb2AreaCritCfg_AebControl_ucNewState, eDefAeb2AreaCritCfg_AebControl_bSetState, eDefAeb2AreaCritCfg_AebControl_bAebReset, eDefAeb2AreaCritCfg_AebControl_uliOthers,
	eDefAeb2AreaCritCfg_AebConfig_uliOthers, eDefAeb2AreaCritCfg_AebConfigKey_uliKey, eDefAeb2AreaCritCfg_AebConfigAit_uliOthers, eDefAeb2AreaCritCfg_AebConfigPattern_ucPatternCcdid, eDefAeb2AreaCritCfg_AebConfigPattern_usiPatternCols,
	eDefAeb2AreaCritCfg_AebConfigPattern_ucReserved, eDefAeb2AreaCritCfg_AebConfigPattern_usiPatternRows, eDefAeb2AreaCritCfg_VaspI2CControl_uliOthers, eDefAeb2AreaCritCfg_DacConfig1_uliOthers, eDefAeb2AreaCritCfg_DacConfig2_uliOthers,
	eDefAeb2AreaCritCfg_Reserved20_uliReserved, eDefAeb2AreaCritCfg_PwrConfig1_ucTimeVccdOn, eDefAeb2AreaCritCfg_PwrConfig1_ucTimeVclkOn, eDefAeb2AreaCritCfg_PwrConfig1_ucTimeVan1On, eDefAeb2AreaCritCfg_PwrConfig1_ucTimeVan2On,
	eDefAeb2AreaCritCfg_PwrConfig2_ucTimeVan3On, eDefAeb2AreaCritCfg_PwrConfig2_ucTimeVccdOff, eDefAeb2AreaCritCfg_PwrConfig2_ucTimeVclkOff, eDefAeb2AreaCritCfg_PwrConfig2_ucTimeVan1Off, eDefAeb2AreaCritCfg_PwrConfig3_ucTimeVan2Off,
	eDefAeb2AreaCritCfg_PwrConfig3_ucTimeVan3Off,

	eDefAeb2AreaGenCfg_Adc1Config1_uliOthers = 6200, eDefAeb2AreaGenCfg_Adc1Config2_uliOthers, eDefAeb2AreaGenCfg_Adc1Config3_uliOthers, eDefAeb2AreaGenCfg_Adc2Config1_uliOthers, eDefAeb2AreaGenCfg_Adc2Config2_uliOthers,
	eDefAeb2AreaGenCfg_Adc2Config3_uliOthers, eDefAeb2AreaGenCfg_Reserved118_uliReserved, eDefAeb2AreaGenCfg_Reserved11C_uliReserved, eDefAeb2AreaGenCfg_SeqConfig1_uliOthers, eDefAeb2AreaGenCfg_SeqConfig2_uliOthers,
	eDefAeb2AreaGenCfg_SeqConfig3_uliOthers, eDefAeb2AreaGenCfg_SeqConfig4_uliOthers, eDefAeb2AreaGenCfg_SeqConfig5_uliOthers, eDefAeb2AreaGenCfg_SeqConfig6_uliOthers, eDefAeb2AreaGenCfg_SeqConfig7_uliReserved,
	eDefAeb2AreaGenCfg_SeqConfig8_uliReserved, eDefAeb2AreaGenCfg_SeqConfig9_ucReserved0, eDefAeb2AreaGenCfg_SeqConfig9_usiFtLoopCnt, eDefAeb2AreaGenCfg_SeqConfig9_bLt0Enabled, eDefAeb2AreaGenCfg_SeqConfig9_bReserved1,
	eDefAeb2AreaGenCfg_SeqConfig9_usiLt0LoopCnt, eDefAeb2AreaGenCfg_SeqConfig10_bLt1Enabled, eDefAeb2AreaGenCfg_SeqConfig10_bReserved0, eDefAeb2AreaGenCfg_SeqConfig10_usiLt1LoopCnt, eDefAeb2AreaGenCfg_SeqConfig10_bLt2Enabled,
	eDefAeb2AreaGenCfg_SeqConfig10_bReserved1, eDefAeb2AreaGenCfg_SeqConfig10_usiLt2LoopCnt, eDefAeb2AreaGenCfg_SeqConfig11_bLt3Enabled, eDefAeb2AreaGenCfg_SeqConfig11_bReserved, eDefAeb2AreaGenCfg_SeqConfig11_usiLt3LoopCnt,
	eDefAeb2AreaGenCfg_SeqConfig11_usiPixLoopCntWord1, eDefAeb2AreaGenCfg_SeqConfig12_usiPixLoopCntWord0, eDefAeb2AreaGenCfg_SeqConfig12_bPcEnabled, eDefAeb2AreaGenCfg_SeqConfig12_bReserved, eDefAeb2AreaGenCfg_SeqConfig12_usiPcLoopCnt,
	eDefAeb2AreaGenCfg_SeqConfig13_ucReserved0, eDefAeb2AreaGenCfg_SeqConfig13_usiInt1LoopCnt, eDefAeb2AreaGenCfg_SeqConfig13_ucReserved1, eDefAeb2AreaGenCfg_SeqConfig13_usiInt2LoopCnt, eDefAeb2AreaGenCfg_SeqConfig14_uliOthers,

	eDefAeb2AreaHk_AebStatus_ucAebStatus = 6400, eDefAeb2AreaHk_AebStatus_ucOthers0, eDefAeb2AreaHk_AebStatus_usiOthers1, eDefAeb2AreaHk_Timestamp1_uliTimestampDword1, eDefAeb2AreaHk_Timestamp2_uliTimestampDword0,
	eDefAeb2AreaHk_AdcRdDataTVaspL_uliOthers, eDefAeb2AreaHk_AdcRdDataTVaspR_uliOthers, eDefAeb2AreaHk_AdcRdDataTBiasP_uliOthers, eDefAeb2AreaHk_AdcRdDataTHkP_uliOthers, eDefAeb2AreaHk_AdcRdDataTTou1P_uliOthers,
	eDefAeb2AreaHk_AdcRdDataTTou2P_uliOthers, eDefAeb2AreaHk_AdcRdDataHkVode_uliOthers, eDefAeb2AreaHk_AdcRdDataHkVodf_uliOthers, eDefAeb2AreaHk_AdcRdDataHkVrd_uliOthers, eDefAeb2AreaHk_AdcRdDataHkVog_uliOthers,
	eDefAeb2AreaHk_AdcRdDataTCcd_uliOthers, eDefAeb2AreaHk_AdcRdDataTRef1KMea_uliOthers, eDefAeb2AreaHk_AdcRdDataTRef649RMea_uliOthers, eDefAeb2AreaHk_AdcRdDataHkAnaN5V_uliOthers, eDefAeb2AreaHk_AdcRdDataSRef_uliOthers,
	eDefAeb2AreaHk_AdcRdDataHkCcdP31V_uliOthers, eDefAeb2AreaHk_AdcRdDataHkClkP15V_uliOthers, eDefAeb2AreaHk_AdcRdDataHkAnaP5V_uliOthers, eDefAeb2AreaHk_AdcRdDataHkAnaP3V3_uliOthers, eDefAeb2AreaHk_AdcRdDataHkDigP3V3_uliOthers,
	eDefAeb2AreaHk_AdcRdDataAdcRefBuf2_uliOthers, eDefAeb2AreaHk_VaspRdConfig_usiOthers, eDefAeb2AreaHk_RevisionId1_uliOthers, eDefAeb2AreaHk_RevisionId2_uliOthers,

	eDefAeb3AreaCritCfg_AebControl_ucReserved0 = 7000, eDefAeb3AreaCritCfg_AebControl_ucNewState, eDefAeb3AreaCritCfg_AebControl_bSetState, eDefAeb3AreaCritCfg_AebControl_bAebReset, eDefAeb3AreaCritCfg_AebControl_uliOthers,
	eDefAeb3AreaCritCfg_AebConfig_uliOthers, eDefAeb3AreaCritCfg_AebConfigKey_uliKey, eDefAeb3AreaCritCfg_AebConfigAit_uliOthers, eDefAeb3AreaCritCfg_AebConfigPattern_ucPatternCcdid, eDefAeb3AreaCritCfg_AebConfigPattern_usiPatternCols,
	eDefAeb3AreaCritCfg_AebConfigPattern_ucReserved, eDefAeb3AreaCritCfg_AebConfigPattern_usiPatternRows, eDefAeb3AreaCritCfg_VaspI2CControl_uliOthers, eDefAeb3AreaCritCfg_DacConfig1_uliOthers, eDefAeb3AreaCritCfg_DacConfig2_uliOthers,
	eDefAeb3AreaCritCfg_Reserved20_uliReserved, eDefAeb3AreaCritCfg_PwrConfig1_ucTimeVccdOn, eDefAeb3AreaCritCfg_PwrConfig1_ucTimeVclkOn, eDefAeb3AreaCritCfg_PwrConfig1_ucTimeVan1On, eDefAeb3AreaCritCfg_PwrConfig1_ucTimeVan2On,
	eDefAeb3AreaCritCfg_PwrConfig2_ucTimeVan3On, eDefAeb3AreaCritCfg_PwrConfig2_ucTimeVccdOff, eDefAeb3AreaCritCfg_PwrConfig2_ucTimeVclkOff, eDefAeb3AreaCritCfg_PwrConfig2_ucTimeVan1Off, eDefAeb3AreaCritCfg_PwrConfig3_ucTimeVan2Off,
	eDefAeb3AreaCritCfg_PwrConfig3_ucTimeVan3Off,

	eDefAeb3AreaGenCfg_Adc1Config1_uliOthers = 7200, eDefAeb3AreaGenCfg_Adc1Config2_uliOthers, eDefAeb3AreaGenCfg_Adc1Config3_uliOthers, eDefAeb3AreaGenCfg_Adc2Config1_uliOthers, eDefAeb3AreaGenCfg_Adc2Config2_uliOthers,
	eDefAeb3AreaGenCfg_Adc2Config3_uliOthers, eDefAeb3AreaGenCfg_Reserved118_uliReserved, eDefAeb3AreaGenCfg_Reserved11C_uliReserved, eDefAeb3AreaGenCfg_SeqConfig1_uliOthers, eDefAeb3AreaGenCfg_SeqConfig2_uliOthers,
	eDefAeb3AreaGenCfg_SeqConfig3_uliOthers, eDefAeb3AreaGenCfg_SeqConfig4_uliOthers, eDefAeb3AreaGenCfg_SeqConfig5_uliOthers, eDefAeb3AreaGenCfg_SeqConfig6_uliOthers, eDefAeb3AreaGenCfg_SeqConfig7_uliReserved,
	eDefAeb3AreaGenCfg_SeqConfig8_uliReserved, eDefAeb3AreaGenCfg_SeqConfig9_ucReserved0, eDefAeb3AreaGenCfg_SeqConfig9_usiFtLoopCnt, eDefAeb3AreaGenCfg_SeqConfig9_bLt0Enabled, eDefAeb3AreaGenCfg_SeqConfig9_bReserved1,
	eDefAeb3AreaGenCfg_SeqConfig9_usiLt0LoopCnt, eDefAeb3AreaGenCfg_SeqConfig10_bLt1Enabled, eDefAeb3AreaGenCfg_SeqConfig10_bReserved0, eDefAeb3AreaGenCfg_SeqConfig10_usiLt1LoopCnt, eDefAeb3AreaGenCfg_SeqConfig10_bLt2Enabled,
	eDefAeb3AreaGenCfg_SeqConfig10_bReserved1, eDefAeb3AreaGenCfg_SeqConfig10_usiLt2LoopCnt, eDefAeb3AreaGenCfg_SeqConfig11_bLt3Enabled, eDefAeb3AreaGenCfg_SeqConfig11_bReserved, eDefAeb3AreaGenCfg_SeqConfig11_usiLt3LoopCnt,
	eDefAeb3AreaGenCfg_SeqConfig11_usiPixLoopCntWord1, eDefAeb3AreaGenCfg_SeqConfig12_usiPixLoopCntWord0, eDefAeb3AreaGenCfg_SeqConfig12_bPcEnabled, eDefAeb3AreaGenCfg_SeqConfig12_bReserved, eDefAeb3AreaGenCfg_SeqConfig12_usiPcLoopCnt,
	eDefAeb3AreaGenCfg_SeqConfig13_ucReserved0, eDefAeb3AreaGenCfg_SeqConfig13_usiInt1LoopCnt, eDefAeb3AreaGenCfg_SeqConfig13_ucReserved1, eDefAeb3AreaGenCfg_SeqConfig13_usiInt2LoopCnt, eDefAeb3AreaGenCfg_SeqConfig14_uliOthers,

	eDefAeb3AreaHk_AebStatus_ucAebStatus = 7400, eDefAeb3AreaHk_AebStatus_ucOthers0, eDefAeb3AreaHk_AebStatus_usiOthers1, eDefAeb3AreaHk_Timestamp1_uliTimestampDword1, eDefAeb3AreaHk_Timestamp2_uliTimestampDword0,
	eDefAeb3AreaHk_AdcRdDataTVaspL_uliOthers, eDefAeb3AreaHk_AdcRdDataTVaspR_uliOthers, eDefAeb3AreaHk_AdcRdDataTBiasP_uliOthers, eDefAeb3AreaHk_AdcRdDataTHkP_uliOthers, eDefAeb3AreaHk_AdcRdDataTTou1P_uliOthers,
	eDefAeb3AreaHk_AdcRdDataTTou2P_uliOthers, eDefAeb3AreaHk_AdcRdDataHkVode_uliOthers, eDefAeb3AreaHk_AdcRdDataHkVodf_uliOthers, eDefAeb3AreaHk_AdcRdDataHkVrd_uliOthers, eDefAeb3AreaHk_AdcRdDataHkVog_uliOthers,
	eDefAeb3AreaHk_AdcRdDataTCcd_uliOthers, eDefAeb3AreaHk_AdcRdDataTRef1KMea_uliOthers, eDefAeb3AreaHk_AdcRdDataTRef649RMea_uliOthers, eDefAeb3AreaHk_AdcRdDataHkAnaN5V_uliOthers, eDefAeb3AreaHk_AdcRdDataSRef_uliOthers,
	eDefAeb3AreaHk_AdcRdDataHkCcdP31V_uliOthers, eDefAeb3AreaHk_AdcRdDataHkClkP15V_uliOthers, eDefAeb3AreaHk_AdcRdDataHkAnaP5V_uliOthers, eDefAeb3AreaHk_AdcRdDataHkAnaP3V3_uliOthers, eDefAeb3AreaHk_AdcRdDataHkDigP3V3_uliOthers,
	eDefAeb3AreaHk_AdcRdDataAdcRefBuf2_uliOthers, eDefAeb3AreaHk_VaspRdConfig_usiOthers, eDefAeb3AreaHk_RevisionId1_uliOthers, eDefAeb3AreaHk_RevisionId2_uliOthers,

	eDefAeb4AreaCritCfg_AebControl_ucReserved0 = 8000, eDefAeb4AreaCritCfg_AebControl_ucNewState, eDefAeb4AreaCritCfg_AebControl_bSetState, eDefAeb4AreaCritCfg_AebControl_bAebReset, eDefAeb4AreaCritCfg_AebControl_uliOthers,
	eDefAeb4AreaCritCfg_AebConfig_uliOthers, eDefAeb4AreaCritCfg_AebConfigKey_uliKey, eDefAeb4AreaCritCfg_AebConfigAit_uliOthers, eDefAeb4AreaCritCfg_AebConfigPattern_ucPatternCcdid, eDefAeb4AreaCritCfg_AebConfigPattern_usiPatternCols,
	eDefAeb4AreaCritCfg_AebConfigPattern_ucReserved, eDefAeb4AreaCritCfg_AebConfigPattern_usiPatternRows, eDefAeb4AreaCritCfg_VaspI2CControl_uliOthers, eDefAeb4AreaCritCfg_DacConfig1_uliOthers, eDefAeb4AreaCritCfg_DacConfig2_uliOthers,
	eDefAeb4AreaCritCfg_Reserved20_uliReserved, eDefAeb4AreaCritCfg_PwrConfig1_ucTimeVccdOn, eDefAeb4AreaCritCfg_PwrConfig1_ucTimeVclkOn, eDefAeb4AreaCritCfg_PwrConfig1_ucTimeVan1On, eDefAeb4AreaCritCfg_PwrConfig1_ucTimeVan2On,
	eDefAeb4AreaCritCfg_PwrConfig2_ucTimeVan3On, eDefAeb4AreaCritCfg_PwrConfig2_ucTimeVccdOff, eDefAeb4AreaCritCfg_PwrConfig2_ucTimeVclkOff, eDefAeb4AreaCritCfg_PwrConfig2_ucTimeVan1Off, eDefAeb4AreaCritCfg_PwrConfig3_ucTimeVan2Off,
	eDefAeb4AreaCritCfg_PwrConfig3_ucTimeVan3Off,

	eDefAeb4AreaGenCfg_Adc1Config1_uliOthers = 8200, eDefAeb4AreaGenCfg_Adc1Config2_uliOthers, eDefAeb4AreaGenCfg_Adc1Config3_uliOthers, eDefAeb4AreaGenCfg_Adc2Config1_uliOthers, eDefAeb4AreaGenCfg_Adc2Config2_uliOthers,
	eDefAeb4AreaGenCfg_Adc2Config3_uliOthers, eDefAeb4AreaGenCfg_Reserved118_uliReserved, eDefAeb4AreaGenCfg_Reserved11C_uliReserved, eDefAeb4AreaGenCfg_SeqConfig1_uliOthers, eDefAeb4AreaGenCfg_SeqConfig2_uliOthers,
	eDefAeb4AreaGenCfg_SeqConfig3_uliOthers, eDefAeb4AreaGenCfg_SeqConfig4_uliOthers, eDefAeb4AreaGenCfg_SeqConfig5_uliOthers, eDefAeb4AreaGenCfg_SeqConfig6_uliOthers, eDefAeb4AreaGenCfg_SeqConfig7_uliReserved,
	eDefAeb4AreaGenCfg_SeqConfig8_uliReserved, eDefAeb4AreaGenCfg_SeqConfig9_ucReserved0, eDefAeb4AreaGenCfg_SeqConfig9_usiFtLoopCnt, eDefAeb4AreaGenCfg_SeqConfig9_bLt0Enabled, eDefAeb4AreaGenCfg_SeqConfig9_bReserved1,
	eDefAeb4AreaGenCfg_SeqConfig9_usiLt0LoopCnt, eDefAeb4AreaGenCfg_SeqConfig10_bLt1Enabled, eDefAeb4AreaGenCfg_SeqConfig10_bReserved0, eDefAeb4AreaGenCfg_SeqConfig10_usiLt1LoopCnt, eDefAeb4AreaGenCfg_SeqConfig10_bLt2Enabled,
	eDefAeb4AreaGenCfg_SeqConfig10_bReserved1, eDefAeb4AreaGenCfg_SeqConfig10_usiLt2LoopCnt, eDefAeb4AreaGenCfg_SeqConfig11_bLt3Enabled, eDefAeb4AreaGenCfg_SeqConfig11_bReserved, eDefAeb4AreaGenCfg_SeqConfig11_usiLt3LoopCnt,
	eDefAeb4AreaGenCfg_SeqConfig11_usiPixLoopCntWord1, eDefAeb4AreaGenCfg_SeqConfig12_usiPixLoopCntWord0, eDefAeb4AreaGenCfg_SeqConfig12_bPcEnabled, eDefAeb4AreaGenCfg_SeqConfig12_bReserved, eDefAeb4AreaGenCfg_SeqConfig12_usiPcLoopCnt,
	eDefAeb4AreaGenCfg_SeqConfig13_ucReserved0, eDefAeb4AreaGenCfg_SeqConfig13_usiInt1LoopCnt, eDefAeb4AreaGenCfg_SeqConfig13_ucReserved1, eDefAeb4AreaGenCfg_SeqConfig13_usiInt2LoopCnt, eDefAeb4AreaGenCfg_SeqConfig14_uliOthers,

	eDefAeb4AreaHk_AebStatus_ucAebStatus = 8400, eDefAeb4AreaHk_AebStatus_ucOthers0, eDefAeb4AreaHk_AebStatus_usiOthers1, eDefAeb4AreaHk_Timestamp1_uliTimestampDword1, eDefAeb4AreaHk_Timestamp2_uliTimestampDword0,
	eDefAeb4AreaHk_AdcRdDataTVaspL_uliOthers, eDefAeb4AreaHk_AdcRdDataTVaspR_uliOthers, eDefAeb4AreaHk_AdcRdDataTBiasP_uliOthers, eDefAeb4AreaHk_AdcRdDataTHkP_uliOthers, eDefAeb4AreaHk_AdcRdDataTTou1P_uliOthers,
	eDefAeb4AreaHk_AdcRdDataTTou2P_uliOthers, eDefAeb4AreaHk_AdcRdDataHkVode_uliOthers, eDefAeb4AreaHk_AdcRdDataHkVodf_uliOthers, eDefAeb4AreaHk_AdcRdDataHkVrd_uliOthers, eDefAeb4AreaHk_AdcRdDataHkVog_uliOthers,
	eDefAeb4AreaHk_AdcRdDataTCcd_uliOthers, eDefAeb4AreaHk_AdcRdDataTRef1KMea_uliOthers, eDefAeb4AreaHk_AdcRdDataTRef649RMea_uliOthers, eDefAeb4AreaHk_AdcRdDataHkAnaN5V_uliOthers, eDefAeb4AreaHk_AdcRdDataSRef_uliOthers,
	eDefAeb4AreaHk_AdcRdDataHkCcdP31V_uliOthers, eDefAeb4AreaHk_AdcRdDataHkClkP15V_uliOthers, eDefAeb4AreaHk_AdcRdDataHkAnaP5V_uliOthers, eDefAeb4AreaHk_AdcRdDataHkAnaP3V3_uliOthers, eDefAeb4AreaHk_AdcRdDataHkDigP3V3_uliOthers,
	eDefAeb4AreaHk_AdcRdDataAdcRefBuf2_uliOthers, eDefAeb4AreaHk_VaspRdConfig_usiOthers, eDefAeb4AreaHk_RevisionId1_uliOthers, eDefAeb4AreaHk_RevisionId2_uliOthers,

	// MEB - NUC
	eDefTcpServerPort = 10000, eDefDHCPv4Enable, eDefIPv4Address, eDefIPv4Subnet, eDefIPv4Gateway,
	eDefIPv4DNS, eDefPusHpPid, eDefPusHpPcat

} EDefaultId;

//! [public function prototypes]
void vClearMebDefault();
bool bClearFeeDefault(alt_u8 ucFee);
void vClearNucDefault();

bool bSetMebDefaultValues(alt_u16 usiDefaultId, alt_u32 uliDefaultValue);
bool bSetFeeDefaultValues(alt_u8 ucFee, alt_u16 usiDefaultId, alt_u32 uliDefaultValue);
bool bSetNucDefaultValues(alt_u16 usiDefaultId, alt_u32 uliDefaultValue);

bool bSetDefaultValues(alt_u16 usiMebFee, alt_u16 usiDefaultId, alt_u32 uliDefaultValue);
//! [public function prototypes]

//! [data memory public global variables - use extern]
extern volatile bool vbDefaultsReceived;
extern volatile alt_u32 vuliExpectedDefaultsQtd;
extern volatile alt_u32 vuliReceivedDefaultsQtd;
extern volatile TDeftMebDefaults vxDeftMebDefaults;
extern volatile TDeftFeeDefaults vxDeftFeeDefaults[N_OF_FastFEE];
extern volatile TDeftNucDefaults vxDeftNucDefaults;
//! [data memory public global variables - use extern]

//! [flags]
//! [flags]

//! [program memory public global variables - use extern]
//! [program memory public global variables - use extern]

//! [macros]
//! [macros]

#endif /* UTILS_DEFAULTS_H_ */
